name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - seaborn
  - theano
  - pymc3
  - scipy
  - mkl-service